name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: "Docker image tag to deploy"
        required: true
        default: "latest"

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: hunter-ecs-cluster
  SERVICE_NAME: hunter-java-service
  TASK_DEF_FAMILY: hunter-task
  CONTAINER_NAME: hunter-container
  ECR_REPO_NAME: huntersamplejavaapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Register ECS Task Definition
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          ECR_URI=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${{ github.event.inputs.IMAGE_TAG }}

          echo "📦 Registering new Fargate-compatible task definition..."
          cat <<EOF > taskdef.json
          {
            "family": "${TASK_DEF_FAMILY}",
            "executionRoleArn": "arn:aws:iam::${ACCOUNT_ID}:role/ecsTaskExecutionRole",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "containerDefinitions": [
              {
                "name": "${CONTAINER_NAME}",
                "image": "${ECR_URI}",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 8081,
                    "protocol": "tcp"
                  }
                ]
              }
            ]
          }
EOF

          aws ecs register-task-definition --cli-input-json file://taskdef.json

      - name: Update ECS Service
        run: |
          echo "🚀 Updating ECS service to use the new task definition..."
          TASK_DEF_ARN=$(aws ecs describe-task-definition \
            --task-definition ${TASK_DEF_FAMILY} \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          aws ecs update-service \
            --cluster ${CLUSTER_NAME} \
            --service ${SERVICE_NAME} \
            --task-definition $TASK_DEF_ARN

      - name: Verify Deployment
        run: |
          echo "🔎 Checking ECS service status..."
          aws ecs describe-services \
            --cluster ${CLUSTER_NAME} \
            --services ${SERVICE_NAME} \
            --query "services[0].deployments"
